### ISSUE TITLE
getBatteryChargeLevel result

### ISSUE THREAD

**Issue by yangjianlin-c** [danilopinotti/esp-battery18650-stats#1]
Hi Danilo,
I try this Library just now, found that the read value of getBatteryChargeLevel is 0 to 10? why not 0 to 100？
If I want to got result from 0 to 100 how to do it? Thanks.

**Comment by danilopinotti** [comment]
Hello @yangjianlin-c!
First of all, thanks for using the lib!

The lib already returns a value between 0 and 100

There are two problems that I think you are having.
- Your code is using the **wrong ADC port or**
- Your code is using the **wrong conversion factor**.
Both are documented in "import and setup" section: https://github.com/danilopinotti/Battery18650Stats#import-and-setup

To find the right conversion factor you will need a voltmeter.
Steps:
1. Get the voltage of the battery with a voltmeter
2. Print the voltage obtained by the lib through `getBatteryVolts` method

If the measurements (lib and voltmeter) are equal, the conversion factor is right. If they aren't, you must increment or decrement the conversion factor until the measurements match up.

PS: I'll add these steps in documentation as soon. Thanks for reporting.

____
Updated:
I added a section named "Troubleshooting" in the documentation.

**Comment by yangjianlin-c** [comment]
Hi  Danilopinotti,
Thank you. My problem solved. It get 0 to 100 values now. I'm not sure how it comes back, because I change the code a lot. And while I run it again some days later, it's OK.
Battery measurement is a tough task. You make it simple, thanks.
