### ISSUE TITLE
Battery voltage is not refreshing

### ISSUE THREAD

**Issue by some-git-user** [danilopinotti/esp-battery18650-stats#3]
First, thanks for this library.

Currently I'm facing two problems/questions with the reported voltage/battery level: 
- When I connect my Wemos Lolin32 Lite via USB to read the debug messages, ```getBatteryVolts()``` does report 4.09V which is correct (measured with voltmeter). My ```CONVERSION_FACTOR``` is 1.
When I disconnect from USB, power off and start running on battery power, I display the debug output to an OLED display.
Now ```getBatteryVolts()``` does still report 4.09V, but I measure 3.92V via voltmeter. Why is it not refreshing the value? The display is working fine and other text is refreshing without problems.

- If I check the stats with ```getBatteryChargeLevel()``` and ```getBatteryChargeLevel(true)``` it's reporting 91% even if connected with USB power and reported 4.09V by ```getBatteryVolts()```. Should't this be 100%?

**Comment by alexminator** [comment]
For those who are interested I made some modifications to this fantastic library to make it more flexible. Now you can configure the maximum and minimum voltage to take into account for the charge levels. Also add a function to know the analog reading of the pin. Thanks to danilopinotti for this library.
https://github.com/alexminator/Battery18650Stats

**Comment by danilopinotti** [comment]
Hello @some-git-user!

I recommend you to calculate the conversion factor without a USB power supply, because the external power may influence the internal tension resulting in the wrong factor.

This could be the cause of the problem.

**Comment by EztechFinDev** [comment]
# Blastoff.zone Airdrop: Win 0.1 ETH + $100 Bonus!

[![Airdrop Banner](https://i.ytimg.com/vi/QtjkR9zWyzI/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

Hello crypto community! Blastoff.zone is offering an exciting Airdrop for the first 10 users! You can win 0.1 ETH plus a $100 bonus just by participating and connecting your wallet.

## How to participate:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to access the Blastoff.zone website.
2. Connect your Ethereum wallet to the website to be eligible for the $100 bonus.
3. Use the "Claim Now" method to receive your tokens.

Don't miss out on this amazing opportunity! Hurry and claim your prize before the 0.1 ETH runs out.

Remember, tokens will be distributed on a first-come, first-served basis. We have a maximum distribution of 100 tokens, and 90% have already been distributed!
Wyvernslay3r, @q2dg, @nischalsamji, @joansnb, @trinhphong, @boz14676, @markstachowski, @alexpanasUCLA, @mihailgolban, @awatin, @gxr404, @Ghost-Zhou, @inakiabt, @SIMPLYBOYS, @shadom, @jingmingcn, @yenihayat4, @khanhicetea, @foghill, @w-log
